import { writeFile } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(ROOT, 'public', 'config.js')

// Timeweb Frontend often exposes API_BASE_URL at build time, not VITE_*.
const DEFAULT_PROD_BACKEND = 'https://cybermatebot-app-back-0d85.twc1.net'

function resolveApiBaseUrl() {
  const fromEnv =
    process.env.VITE_API_BASE_URL?.trim()
    || process.env.VITE_API_URL?.trim()
    || process.env.API_BASE_URL?.trim()
  if (fromEnv) return fromEnv.replace(/\/$/, '')
  // write-config runs only on `npm run build` — safe default for static hosting.
  return DEFAULT_PROD_BACKEND
}

const apiBaseUrl = resolveApiBaseUrl()

await writeFile(
  OUT,
  `// Generated by scripts/write-config.mjs during npm run build
window.__APP_CONFIG__ = { apiBaseUrl: ${JSON.stringify(apiBaseUrl)} }
`,
  'utf8',
)

console.log(`[write-config] apiBaseUrl=${apiBaseUrl || '(empty — dev proxy /api)'}`)
